spring:
  application:
    name: nes-api-gateway
    
#Zuul routes
zuul:
 sensitiveHeaders: Cookie,Set-Cookie,Authorization
 routes:
  product: 
   path: /products/**
   service-id: nes-product
   stripPrefix: false
  order: 
   path: /orders/**
   service-id: nes-order
   stripPrefix: false
  cart:
   path: /cart/**
   service-id: nes-order
   stripPrefix: false
  delivery:
   path: /delivery/**
   service-id: nes-delivery
   stripPrefix: false
  user: 
   path: /users/**
   service-id: nes-user
   stripPrefix: false
  payment:
   path: /payment/**
   service-id: nes-payment
   stripPrefix: false
   
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 10000
  SocketTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST:http://localhost:8761/eureka/}
      
server:
  port: 8090
  
auth: 
 key: axcafdagaddff12345