spring:
  profiles: 
    active: ${ACIVE_PROFILE}
  rabbitmq: 
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:8087}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST}