version: "3"

services: 

  rabbitmq: 
     image: rabbitmq:3-management
     hostname: "rabbitmq"
     ports:
     - "8087:5672"
     - "8088:15672"
  nes-discovery-server: 
     image: 3147181/nes-discovery-server:v1
     ports: 
     - "8761:8761"
  nes-order: 
     image: 3147181/nes-order:v1
     ports:
     - "8082:8082"
     environment: 
     - EUREKA_SERVER_HOST=http://nes-discovery-server:8761/eureka/
     - RABBITMQ_HOST=rabbitmq
     - RABBITMQ_PORT=5672
     depends_on:
     - nes-discovery-server
     - rabbitmq
  nes-user: 
     image: 3147181/nes-user:v1
     ports:
     - "8085:8085"
     environment: 
     - EUREKA_SERVER_HOST=http://nes-discovery-server:8761/eureka/
     depends_on:
     - nes-discovery-server
     - rabbitmq
  nes-api-gateway: 
     image: 3147181/nes-api-gateway:v1
     ports:
     - "8080:8090"
     environment: 
     - EUREKA_SERVER_HOST=http://nes-discovery-server:8761/eureka/
     depends_on:
     - nes-discovery-server
  nes-delivery: 
     image: 3147181/nes-delivery:v1
     ports:
     - "8081:8081"
     environment: 
     - EUREKA_SERVER_HOST=http://nes-discovery-server:8761/eureka/
     - RABBITMQ_HOST=rabbitmq
     - RABBITMQ_PORT=5672
     depends_on:
     - nes-discovery-server
     - rabbitmq
     - nes-order
  nes-payment: 
     image: 3147181/nes-payment:v1
     ports:
     - "8083:8083"
     environment: 
     - EUREKA_SERVER_HOST=http://nes-discovery-server:8761/eureka/
     - RABBITMQ_HOST=rabbitmq
     - RABBITMQ_PORT=5672
     depends_on:
     - nes-discovery-server
     - rabbitmq
     - nes-order
  nes-product: 
     image: 3147181/nes-product:v1
     ports:
     - "8084:8084"
     environment: 
     - EUREKA_SERVER_HOST=http://nes-discovery-server:8761/eureka/
     - RABBITMQ_HOST=rabbitmq
     - RABBITMQ_PORT=5672
     depends_on:
     - nes-discovery-server
     - rabbitmq
     - nes-order
 