spring:
  profiles: 
    active: ${ACIVE_PROFILE}
  rabbitmq: 
    host: ${RABBITMQ_HOST:localhost}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_HOST:http://localhost:8761/eureka}